FROM nginx:alpine

# Configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivos estáticos del frontend
COPY index.html /usr/share/nginx/html/
COPY admin.html /usr/share/nginx/html/
COPY reportes.html /usr/share/nginx/html/
COPY manifest.json /usr/share/nginx/html/
COPY icono-192.png /usr/share/nginx/html/
COPY icono-512.png /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
